//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nasled
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class1.
    /// </summary>
    // *** Start programmer edit section *** (NewClass1 CustomAttributes)

    // *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [Caption("New class1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass1E", new string[] {
            "Код as \'Код\'",
            "Строка as \'Строка\'"})]
    [View("NewClass1L", new string[] {
            "Код as \'Код\'",
            "Строка as \'Строка\'"})]
    public class NewClass1 : IIS.Nasled.NewClass2
    {
        
        private int fКод;
        
        private string fСтрока;
        
        // *** Start programmer edit section *** (NewClass1 CustomMembers)

        // *** End programmer edit section *** (NewClass1 CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (NewClass1.Код CustomAttributes)

        // *** End programmer edit section *** (NewClass1.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (NewClass1.Код Get start)

                // *** End programmer edit section *** (NewClass1.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (NewClass1.Код Get end)

                // *** End programmer edit section *** (NewClass1.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass1.Код Set start)

                // *** End programmer edit section *** (NewClass1.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (NewClass1.Код Set end)

                // *** End programmer edit section *** (NewClass1.Код Set end)
            }
        }
        
        /// <summary>
        /// Строка.
        /// </summary>
        // *** Start programmer edit section *** (NewClass1.Строка CustomAttributes)

        // *** End programmer edit section *** (NewClass1.Строка CustomAttributes)
        [StrLen(255)]
        public virtual string Строка
        {
            get
            {
                // *** Start programmer edit section *** (NewClass1.Строка Get start)

                // *** End programmer edit section *** (NewClass1.Строка Get start)
                string result = this.fСтрока;
                // *** Start programmer edit section *** (NewClass1.Строка Get end)

                // *** End programmer edit section *** (NewClass1.Строка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass1.Строка Set start)

                // *** End programmer edit section *** (NewClass1.Строка Set start)
                this.fСтрока = value;
                // *** Start programmer edit section *** (NewClass1.Строка Set end)

                // *** End programmer edit section *** (NewClass1.Строка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1E", typeof(IIS.Nasled.NewClass1));
                }
            }
            
            /// <summary>
            /// "NewClass1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1L", typeof(IIS.Nasled.NewClass1));
                }
            }
        }
    }
}
